apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: schema-registry

resources:
- ./namespace.yaml

helmCharts:
  - name: schema-registry
    releaseName: schema-registry
    namespace: schema-registry
    version: 14.1.1
    repo: https://charts.bitnami.com/bitnami
    valuesInline:
      kafka:
        enabled: false
      externalKafka:
        brokers: ["PLAINTEXT://kafka.kafka.svc:9092"]
