apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: druid

resources:
- ./namespace.yaml

helmCharts:
  - name: druid
    releaseName: druid
    namespace: druid
    version: 1.4.0
