apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka

resources:
- ./namespace.yaml

helmCharts:
  - name: kafka
    releaseName: kafka
    namespace: kafka
    version: 18.5.0
    repo: https://charts.bitnami.com/bitnami
