apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml

helmCharts:
  - name: ingress-nginx
    namespace: ingress-nginx
    releaseName: ingress-nginx
    version: 4.8.0
    repo: https://kubernetes.github.io/ingress-nginx
