apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: localstack

resources:
- ./namespace.yaml

helmCharts:
  - name: localstack
    releaseName: localstack
    namespace: localstack
    repo: https://localstack.github.io/helm-charts
