apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airbyte

resources:
- ./namespace.yaml

helmCharts:
  - name: airbyte
    releaseName: airbyte
    namespace: airbyte
    repo: https://airbytehq.github.io/helm-charts
