apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pact

resources:
- ./namespace.yaml

helmCharts:
  - name: pact-broker
    releaseName: pact-broker
    namespace: pact
    repo: https://pact-foundation.github.io/pact-broker-chart/
    valuesInline:
      postgresql:
        enabled: true
      broker:
        config:
          logLevel: debug
          httpDebugLoggingEnabled: true
          baseUrls: 'http://pact.local http://pact.local:9292 http://localhost http://localhost:9292 http://127.0.0.1 http://127.0.0.1:9292 http://0.0.0.0 http://0.0.0.0:9292'
